apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: github
      eventName: nodejs
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: kaniko-build1
                labels:
                  workflows.argoproj.io/archive-strategy: "false"
              spec:
                entrypoint: full
                serviceAccountName: argo
                volumes:
                - name: kaniko-secret
                  secret:
                    secretName: regcred
                    items:
                     - key: .dockerconfigjson
                       path: config.json
                templates:
                - name: full
                  dag:
                    tasks:
                    - name: build-container-image
                      templateRef:
                        name: container-image
                        template: build-kaniko-git
                        clusterScope: true
                      arguments:
                        parameters:
                        - name: app_repo
                          value: git://github.com/sathyap0104/nodejs-welcome.git
                        - name: container_image
                          value: sathyap04/kaniko
                        - name: container_tag
                          value: "1.1.1"
                - name: build-kaniko-git
                  inputs:
                    parameters:
                    - name: app_repo
                    - name: container_image
                    - name: container_tag
                  container:
                    image: gcr.io/kaniko-project/executor:debug
                    command: [/kaniko/executor]
                    args:
                     - --context={{inputs.parameters.app_repo}}
                     - --destination={{inputs.parameters.container_image}}:{{inputs.parameters.container_tag}}
                     - --force
                    volumeMounts:
                      - name: kaniko-secret
                        mountPath: /kaniko/.docker/